author:
  email: wei.surya@gmail.com
  name: Soen Surya Soenaryo
color:
  brandColors:
    - '#191919'
    - '#0C1570'
    - '#0B2886'
    - '#1898D7'
    - '#18C6E8'
  brandStrength: 0.4597370324190706
  lightness: 0.0388363569509238
  rhythmicContrast: 0.989964110776782
  saturation: 0.2966265541035682
layout_spectrum: 1
name: suryasoenaryo
typography_spectrum: 0.46875
