layout_spectrum: 0.5614732215180993
typography_spectrum: 0.2539959482382983
color:
  brandStrength: 0.4597370324190706
  lightness: 0.0388363569509238
  saturation: 0.2966265541035682
  rhythmicContrast: 0.989964110776782
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
name: suryasoenaryo
