typography_spectrum: 0.3902402308303863
color:
  brandColors:
    - '#191919'
    - '#0C1570'
    - '#0B2886'
    - '#1898D7'
    - '#18C6E8'
  brandStrength: 0.662006
  lightness: 0.759868
  rhythmicContrast: 1
  saturation: 0.568256
layout_spectrum: 0.0988586291205138
author:
  email: wei.surya@gmail.com
  name: Soen Surya Soenaryo
name: suryasoenaryo
navigation:
  - id: 'https://www.facebook.com/surya.soenaryo'
    url: 'https://www.facebook.com/surya.soenaryo'
    name: Facebook
    type: external
  - id: 'https://twitter.com/wei_surya'
    url: 'https://twitter.com/wei_surya'
    name: Twitter
    type: external
  - id: 'https://www.instagram.com/wei_surya'
    url: 'https://www.instagram.com/wei_surya'
    name: Instagram
    type: external
